### ISSUE TITLE
Username only lowercase?

### ISSUE THREAD

**Issue by SaschaMzH** [remy/mit-license#1034]
Hi All,

first of all. Thanks for your work.
My user file (SaschaMzH) was merged but the mit license page has still the 'copyright holder' inserted.
Wenever I open the page http://SaschaMzH.mit-license.org/ but i will redirect to https://saschamzh.mit-license.org/ - could this be a problem?
I did not found any limitations about case sensitive user files.

Thanks
Sascha

**Comment by remy** [comment]
I've got a feeling you're right. Domains aren't case sensitive (in fact, i think they drop to lowercase), but filenames are, so I think we need to do some kind of check to ensure the PRs include filenames in lowercase.

**Comment by SaschaMzH** [comment]
Ok, thanks.
I created a new pull request to get it work and extended the documentation a little bit to let other people know that the username file must be written lowercase.
