### ISSUE TITLE
Update my license please

### ISSUE THREAD

**Issue by wcamarao** [remy/mit-license#1133]
Current: functioncallback: https://functioncallback.mit-license.org/
New: wcamarao: https://wcamarao.mit-license.org/

New email: wagner@camarao.io
New URL: https://camarao.io
Theme: default

You can confirm email change by sending hi to functioncallback@gmail.com, then wait for autoreply.

Thanks

**Comment by remy** [comment]
Super late reply, but you'll need to do a pull request to change it.
