### ISSUE TITLE
subdomain not created

### ISSUE THREAD

**Issue by MR-Mostafa** [remy/mit-license#1187]
Hello,
My address has not been created But my commit is confirmed & merged.
https://mr-mostafa.mit-license.org/

**Comment by squanto** [comment]
<img width="1308" alt="screen shot 2018-04-10 at 5 13 38 pm" src="https://user-images.githubusercontent.com/973173/38583902-8c315e6c-3ce2-11e8-8919-caa745e26a12.png">

yea it was 😃
