### ISSUE TITLE
License not live!!

### ISSUE THREAD

**Issue by Mayankjh** [remy/mit-license#1246]
I made the the json file called "mayankjha.json" and also created a pull request that was merged but the license dosen't to be live yet why?
am I missing something? 
![image](https://user-images.githubusercontent.com/29487575/42102191-d7215280-7be2-11e8-8023-31636e13a499.png)

**Comment by squanto** [comment]
yes? https://mayankjha.mit-license.org/

**Comment by Mayankjh** [comment]
no i mean the credentials on the license should appear. the pic above does not has my credentials for eg.
![image](https://user-images.githubusercontent.com/29487575/42136151-fe88412a-7d73-11e8-800a-8d915fe0f846.png)
if you type any name ahead of the link  https://**.mit-license.org/ in place of ** the pic in above comment comes which should be like in this comment....
hope you are getting it...

**Comment by squanto** [comment]
oh okok. Your config wasn't getting picked up because we don't handle upper-case files 😄 . Looks like the page is updated. Does everything look good from your end @Mayankjh ?

**Comment by Mayankjh** [comment]
i checked the link everything is good thanks @squanto
