### ISSUE TITLE
user was created but not existing now.

### ISSUE THREAD

**Issue by bitmxittz** [remy/mit-license#1265]
Hi,
I sent pull request bitmxittz.json and user was created but bitmxittz.mit-license.org did not show copyright info.
I sent pull request as following
curl -d'{ "copyright": "Bitmxittz Developers", "url": "https://bitmxittz.com", "email": "contact@bitmxittz.com", "theme": "flesch", "gravatar": true }' https://bitmxittz.mit-license.org

then i commited changes to
{ "copyright": "Bitmxittz Developers", "url": "https://bitmxittz.com", "email": "contact@bitmxittz.com", "theme": "flesch", "gravatar": true }

still didn't work. so deleted bitmxittz.json and sent another request new pull request shows "All checks have passed" but user is not found in https://github.com/remy/mit-license/tree/master/users

Thank in advance for assistance in getting own mit-license page bitmxittz.mit-license.org with copyright info.

Thanks.

**Comment by Richienb** [comment]
Requesting a license via the http request doesn't seem to add a file to the `users` folder.

**Comment by Richienb** [comment]
@bitmxittz Since everything seems to be working now, I'm going to go ahead and close this issue.
