### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Krinkle** [remy/mit-license#1272]
Hi @Remy,

First of all, thanks for this initiative. I've been using it for many years and have adopted it in various projects and often recommend it.

It took me by surprise the other day when looking at GA's tracking net for one of my browsing sessions, to see it also included mit-license.org.

Perhaps you're an active user of the GA metrics and I suppose I have no ask in that case, but if they're not critical, perhaps you'd be willing to reconsider its use for mit-license.org, in favour of something simpler, e.g. server-side based, or image-based.

Alternatively, perhaps it could be limited to the landing page of the base domain only, and/or specific subdomains only.

**Comment by Richienb** [comment]
According to Google LighthouseeGoogle Analytics seems to be hogging 300ms of page load time due to the absence of a `preconnect` or `dns-prefetch` rel tag. Here is the full warning:
```
Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. Learn more.
```
