### ISSUE TITLE
Gravatar needs an alt attribute

### ISSUE THREAD

**Issue by Richienb** [remy/mit-license#1286]
According to Google Lighthouse, the gravatar image needs an alt attribute which should be easily added via the `name` key in the JSON file.

**Comment by remy** [comment]
Change wanted here: https://github.com/remy/mit-license/blob/master/index.php#L64

**Comment by Richienb** [comment]
I'm going to include this fix in conjunction with all the rest. I'll publish a draft PR pretty soon.

**Comment by remy** [comment]
👍
