### ISSUE TITLE
URL encoding email address in txt license

### ISSUE THREAD

**Issue by virgilwashere** [remy/mit-license#1375]
The `license.txt` URL of any subdomain with an email address produces URL encoded angle brackets (`< >`) around the email address.

Link: https://rem.mit-license.org/license.txt

```
The MIT License (MIT)

Copyright © 2019 Remy Sharp, https://remysharp.com &lt;remy@remysharp.com&gt;
```

Link: https://virgilwashere.mit-license.org/2018/+ISC/license.txt

```
The ISC License (ISC)

Copyright © 2018-2019 Virgil &lt;virgil@virgilwashere.co&gt;
```

Link: https://adamroberts.mit-license.org/license.txt

```
The MIT License (MIT)

Copyright © 2019 Adam Roberts
```

**Comment by Richienb** [comment]
@virgilwashere Nice catch!
