### ISSUE TITLE
Open Sans Theme

### ISSUE THREAD

**Issue by anselal** [remy/mit-license#1377]
Hi there,

is the theme referenced correct in my json ?

https://github.com/remy/mit-license/blob/054b6b76c72bdab2238d04c8935d7519900a7926/users/soulis.json#L7

I am not sure my [license ](https://soulis.mit-license.org/) uses the theme

**Comment by Richienb** [comment]
It should be `open-sans` not `opensans`. Fixed!

**Comment by anselal** [comment]
Cool, thnx !!
