### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by floydpink** [remy/mit-license#1400]
It looks like there is something wrong with the current deployment - https://mit-license.org/ (and all subdomains) is returning this:

![image](https://user-images.githubusercontent.com/171072/79092178-0daaa700-7d1e-11ea-8762-81371718c502.png)

Thank you!

**Comment by remy** [comment]
Can you try again, I'm getting it working - it might have been a temporary outage

**Comment by Richienb** [comment]
Looks like it just fixed itself. Time to close.

**Comment by floydpink** [comment]
@Richienb - just curious, did this reverted commit have anything to do with the error?

https://github.com/remy/mit-license/commit/e528c75316393e4efbb80bc615a52987907e321a

**Comment by Richienb** [comment]
@floydpink Probably. I'm not a Heroku user but it looks like the package manager to be used is detected based on the lock file and having none would break it somehow.
