### ISSUE TITLE
Interest in moving to Vercel?

### ISSUE THREAD

**Issue by Richienb** [remy/mit-license#1420]
@remy Since [Vercel](https://vercel.com) (Zeit) now supports [wildcard domains](https://vercel.com/blog/wildcard-domains), is there any interest in moving to it to reduce maintenance costs?

**Comment by remy** [comment]
I've considered it (long ago), but not sure it's worthwhile at this point. There's also limitations around what can be run due to the serverless arch. Maybe worth revisiting in 5 years (not kidding!)

**Comment by Richienb** [comment]
What sort of limits are we talking?

**Comment by remy** [comment]
Portability (as much as I love vercel it's non portable).

Reading and minip files during serverless calls (this, I think, is
possible, but not straight forward, and I don't recall if it works when you
want to use the very pared down serverless functions).

I'm also not sure how the SSL and wild domains work in practice, I've got a
sneaky suspicion that the unlimited cnames are applied on demand, rather
than transparently.

Finally, it'll eat into my own credit on Zeit (or someone else's) whereas
as heroku is paid for and done.
