### ISSUE TITLE
User metadata not persisting

### ISSUE THREAD

**Issue by ErinMorelli** [remy/mit-license#1437]
I registered the user "erin-morelli" a little over a week ago, here's the commit: https://github.com/remy/mit-license/commit/cd2a579987055411c80d4c219de4a7119bb60973

Initially the url https://erin-morelli.mit-license.org/ worked correctly, but when I visited it today, it appears that the site is using the default null values instead of populating with my user metadata.

Looks like the CI tests have been failing since Aug. 12 (https://github.com/remy/mit-license/commit/87f98c9de925ce6e08a38275e5bbda2cd35b4273) not sure if that's at all related?

**Comment by Richienb** [comment]
I removed the buggy user file, see if that helps https://github.com/remy/mit-license/commit/5279ad62fa119f7ac422fd02a797308720403298

**Comment by Richienb** [comment]
Working now.
