### ISSUE TITLE
Deployment failed?

### ISSUE THREAD

**Issue by Richienb** [remy/mit-license#1450]
@remy I did a refactor of mit-license and now Heroku isn't deploying anymore even though all the tests are passing and the site still works. Can you check the deployment logs?

**Comment by remy** [comment]
Oh, I had wondered why it had stopped deploying…

**Comment by remy** [comment]
This is from the logs:

```
-----> Installing dependencies

       Installing node modules (yarn.lock)

       yarn install v1.22.10

       [1/4] Resolving packages...

       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

-----> Build failed

 !     Outdated Yarn lockfile

       Your application contains a Yarn lockfile (yarn.lock) which does not

       match the dependencies in package.json. This can happen if you use npm

       to install or update a dependency instead of Yarn.

       Please run the following command in your application directory and check

       in the new yarn.lock file:

       $ yarn install

       $ git add yarn.lock

       $ git commit -m "Updated Yarn lockfile"

       $ git push heroku main 
```

**Comment by Richienb** [comment]
Looks like the lockfile was out of date - should be [fixed](https://github.com/remy/mit-license/commit/de7cf2e19f99502ac7633446af2fefefff832500) in the next deployment.

Did you see #1420?

**Comment by Richienb** [comment]
Deployment succeeded!

**Comment by Richienb** [comment]
@remy The site is now resolving with an application error on runtime. How do these errors only occur in production?

**Comment by remy** [comment]
Just checked and I'm seeing it render. What URLs are you seeing it failing on?

**Comment by Richienb** [comment]
https://mit-license.org/

**Comment by Richienb** [comment]
Wait a minute, it's now working. Before it was spitting out server errors left to right.

**Comment by remy** [comment]
It might be an intermittent error, I'll have to use my desktop to tail the
logs to see if I can catch it.

Did you test the user creation against your refactor?

**Comment by Richienb** [comment]
A user was created 3 minutes ago on the deployed refactor so user creation must be working.
