### ISSUE TITLE
A tool to hack camera from termux 

### ISSUE THREAD

**Issue by noshock** [remy/mit-license#1466]
AVAILABLE ON:

•TERMUX

TESTED ON :

•TERMUX

REQUIREMENTS :

•internet

•php

•storage 400 mb

•ngrok

FEATURES :

•[+] Real camera hacking

•[+] Updated maintenance

•[+] Ngrok link

•[+] Easy for Beginners

INSTALLATION [Termux] :

•apt-get update -y

•apt-get upgrade -y

• pkg install python -y

• pkg install python2 -y

• pkg install git -y

• pip install lolcat

• git clone      https://github.com/noob-hackers/grabcam

• cd $HOME

• ls

• cd grabcam

• ls

• bash grabcam.sh

to see captured image >>>>

ls
mv(image name with .png) /sdcard

Now go and check your gallery for victim image.....

SCREEN SHOTS [TERMUX]
![IMG_20210311_145046_635.jpg](https://user-images.githubusercontent.com/72062898/110764964-ae308080-8279-11eb-9262-e023f133b95f.jpg)
![IMG_20210311_145043_041.jpg](https://user-images.githubusercontent.com/72062898/110765008-bab4d900-8279-11eb-916f-378fb5fa73ca.jpg)

**Comment by remy** [comment]
lolwat.
