### ISSUE TITLE
Modifying the licence

### ISSUE THREAD

**Issue by filip2cz** [remy/mit-license#1526]
Can I modify the MIT License for my own licensing needs and then continue to use the license under a different name such as FORK?

**Comment by Richienb** [comment]
You can do whatever the license permits, which I believe includes this.

**Comment by filip2cz** [comment]
> You can do whatever the license permits, which I believe includes this.

The license doesn't mention anything like that, however, assuming the license is licensed by itself, then I would have to include the original license when modifying it, which isn't great, because the moment I didn't want commercial use, for example, the two licenses would contradict each other.

**Comment by Richienb** [comment]
The code that communicates the license is MIT Licensed. I believe that MIT License allows the license that is communicated to be changed.

**Comment by filip2cz** [comment]
ok, thanks
