### ISSUE TITLE
Can you add me to the system?

### ISSUE THREAD

**Issue by privatedev11** [remy/mit-license#1547]
Can't make a pull request for some reason, says there's nothing to compare

{
  "copyright": "PrivateMe",
  "url": "https://privatedev11.github.io",
  "email": "busaruba2011services@zohomail.com",
  "format": "html",
  "license": "mit",
  "theme": "hacker",
  "gravatar": true
}

**Comment by Richienb** [comment]
What do you want to name the file?

**Comment by privatedev11** [comment]
PrivateMe

privateme.bio.link
________________________________

**Comment by Richienb** [comment]
https://github.com/remy/mit-license/commit/cb5d866d5a640f45c309bb13b329a89498aeb22d
