### ISSUE TITLE
Deployment doesn't seem to be working for a while now

### ISSUE THREAD

**Issue by AsPulse** [remy/mit-license#1584]
(although it is possible that this may just be a slow deploy)

The last deployed commit was this one a little over two months ago:
d7a1114963d34dcf52035276af5cc70d90c86704 ( https://urosevic.mit-license.org/ )

It appears that no users have been deployed since this...

ex.)
0e91097f98b8fa93a30b1da5ba6e39a2348135e8 ( https://tamer.mit-license.org/ )
e76fbf9284aef341c428df9f5f5795ea48d4ae60 ( https://nariakiiwatani.mit-license.org/ )
... (and 7 users)

**Comment by Richienb** [comment]
@remy The deployment status is no longer appearing for later commits. Could you check Heroku?

**Comment by AntonyBi** [comment]
It's not worked for me too. My license page is https://antonybi.mit-license.org/

**Comment by Richienb** [comment]
@remy Friendly ping :)

**Comment by sebastianst** [comment]
Can confirm, my [`yieldgate` PR](https://github.com/remy/mit-license/pull/1599) was recently merged, but https://yieldgate.mit-license.org/ still shows the generic license.

**Comment by remy** [comment]
I'll take a look at the heroku server logs shortly

**Comment by gillyspy** [comment]
same here

**Comment by arashi-dev** [comment]
This issue still exists. https://arash-jahanbakhshan.mit-license.org/

**Comment by RapidCompiler** [comment]
Both the self-service generator website and the curl command aren't working for me. The website says "JSON requires copyright property and value". The curl command doesn't seem to be allowing addition of multiple copyright holders.

PRs don't seem to be working for anyone as well. Has there been any updates? @remy Kindly help :)

**Comment by Richienb** [comment]
@remy Would it be possible to give me access to view the Heroku logs?

**Comment by remy** [comment]
@Richienb yep, just done that - I should have done that months and months ago!

**Comment by Richienb** [comment]
@remy It seems like deployment needs to be set back up again at https://dashboard.heroku.com/apps/mit-license/deploy/github

**Comment by remy** [comment]
Sorry - read this at a stupid time and instantly forgot.

I've reconnected and deployed.

**Comment by Richienb** [comment]
Thank you!

The site is working again
