### ISSUE TITLE
Curl add user failing with 'JSON requires "copyright" property and value'

### ISSUE THREAD

**Issue by ghousseyn** [remy/mit-license#532]
curl -d '{"copyright":"myname"}' http://name.mit-license.org
This seems to be a permanent failure on my machine (see version bellow)

I'm guessing this is the problem
property_exists($data, 'copyright')

I'm wondering why you're checking the object rather than the array with isset() ?
Something like this:

$data = json_decode(file_get_contents('php://input'),true);
    if (!isset($data['copyright']) {
      Throw new Exception('>>> JSON requires "copyright" property and value');
    }

Thank you

--Version information 

curl 7.20.0 (i386-pc-win32) libcurl/7.20.0 OpenSSL/0.9.8o zlib/1.2.3
Protocols: dict file ftp ftps http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS Largefile NTLM SSL libz

**Comment by benniemosher** [comment]
@remy It looks like you committed a patch for this. Should we go ahead and close out this issue then? @ghousseyn Does your issue appear to be solved with the patch that @remy submitted?

**Comment by nikulifuturz** [comment]
@remy how to create own MIT License URL can you please guide me on same.

Eg : http://rem.mit-license.org

**Comment by Richienb** [comment]
@nikulifuturz Go [here](https://github.com/remy/mit-license/new/master/users) then name the file to anything but end it with `.json` (for example: `richienb.json`) and insert your configuration.

For example, my configuration is:

```json
{
  "copyright": "Richie Bendall, https://www.richie-bendall.ml",
  "url": "https://www.richie-bendall.ml",
  "email": "richiebendall@gmail.com",
  "format": "html",
  "gravatar": true,
  "theme": "material-indigo"
}
```

**Comment by Richienb** [comment]
It now seems that this issue has been fixed. If not, #1355 should further fix things.
