### ISSUE TITLE
Recent commits are not deployed

### ISSUE THREAD

**Issue by teppeis** [remy/mit-license#632]
I have confirmed that https://github.com/remy/mit-license/commit/ddbd03bd8f8476d21bc8e8f7efd563cd30e92914 (28 Dec 2014) is deployed to http://karami.mit-license.org/, but later commits don't seem to be deployed.

**Comment by iamale** [comment]
+1.

**Comment by teppeis** [comment]
@remy Any merged pull-reqs were not deployed.
For example, followings are recent 10 pull-reqs.

* #648 none http://dartokloning.mit-license.org/
* #647 not updated http://eduardorabelo.mit-license.org/
* #646 not updated http://xight.mit-license.org/
* #645 none http://s-a.mit-license.org/
* #644 none http://minidfx.mit-license.org/
* #643 not updated (invalid filename) http://jenish.mit-license.org/
* #642 not updated http://jprice.mit-license.org/
* #641 none http://johnschult.mit-license.org/
* #640 not updated http://if.mit-license.org/
* #639 none http://zzzzbov.mit-license.org/

**Comment by s-a** [comment]
You can ignore my pull request. It simply takes too much time to merge and deploy here. Seems the repo is not supported any more. I created my own repo at https://github.com/s-a/license. Feel free to contribute there. Greetings!

**Comment by remy** [comment]
All fixed. Sorry, the git pull got out of whack.

**Comment by teppeis** [comment]
@remy thanks!

**Comment by iamale** [comment]
@remy :+1::+1::+1::+1:, thank you!
