### ISSUE TITLE
Multiple license-holders?

### ISSUE THREAD

**Issue by Efreak** [remy/mit-license#659]
I've got a forked project. Tehcnically I can't say that the sole licensor of the project is the original creator, as several people have made large contributions. Any chance of allowing an array to be passed, instead of just a single licensor?

**Comment by remy** [comment]
Sure, it's worth seeing a PR off your fork to see how it would work.

**Comment by benniemosher** [comment]
@Efreak I do not see your PR yet. Is there anyway that you can create that so that we can see what it would look like?

**Comment by Efreak** [comment]
@benniemosher the fork in question wasn't this project, it's a fork of another project. I don't actually have any changes in my fork of this project--I had intended to take a look at it, but haven't actually done anything yet.

**Comment by benniemosher** [comment]
I think if you want to be able to pass in an array the code might have to look something like this below:

```
{
  "copyright": [
    {
      name: "Remy Sharp",
      address: "me@mysite.com"
    },
    {
      name: "Bennie Mosher",
      address: "me@mysite.com"
    }
  ], 
  "url": "http://remysharp.com",
  "format": "txt"
}

```

That would allow you to keep each name and address separate from each other and on the backend be able to differ them from each other.

**Comment by Efreak** [comment]
That's the approach I've taken. I've allowed for setting the gravatar address directly in the gravatar property itself, since there's no longer any need for a root-level email address (this also allows setting up a gravatar at a single-use email address for a project-level gravatar).

The old format should continue to work just fine, however the new format is as follows below.
```javascript
{
	copyright: [
		name: "Anonymous",
		url: "http://www.github.com",
		email: "some@email.address"
	],
	format: "html",
	gravatar: "some@email.address",
	version: "somehash",
	theme: "flesch"
}
```
  
Some future suggestions since this is now a multi-user copyright:
- Instead of gravatar (or better, alongside it--to prevent breakage), allow a url for a project logo
- Use an [📧](http://emojipedia.org/e-mail-symbol/) for the email link, rather than displaying it, otherwise this could get rather long for large projects.
- Validate the email field.
- This would be quite a bit more complex, but it should still be relatively simple to allow copyright changing via a webpage, with authorization through github openid/oauth/whatever they use.
