### ISSUE TITLE
Upgrade tracking to GA Universal?

### ISSUE THREAD

**Issue by hubdotcom** [remy/mit-license#668]
I noticed the core LICENSE.html uses the old ga.js - this will eventually be deprecated and should be upgraded to Universal Analytics - see here for instructions https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs

Also, since this loads asynchronously, it's recommended by Google to put it just before the closing </head> to ensure a higher percentage of visitors are tracked. This does not block page rendering and thus has no impact on performance.

**Comment by benniemosher** [comment]
@hubdotcom Would you be interested in submitting a PR to update this code?

**Comment by kolobus** [comment]
Did it :)

**Comment by remy** [comment]
Oh, this was done a while ago.
