### ISSUE TITLE
My mit-license.org site doesn't have my info

### ISSUE THREAD

**Issue by AllThingsSmitty** [remy/mit-license#686]
PR [#681](https://github.com/remy/mit-license/pull/681) with my user information was merged but http://allthingssmitty.mit-license.org/ doesn't have my information. Is there anything else I need to do?

**Comment by zzzzBov** [comment]
I'm having the same issue with http://zzzzbov.mit-license.org.

**Comment by AllThingsSmitty** [comment]
@remy any thoughts about this? +@zzzzBov

**Comment by GGG-KILLER** [comment]
I have the same problem, the pull request got merged but the page is still with the old information

**Comment by remy** [comment]
Fixed. Somehow the git hook got out of whack.

**Comment by AllThingsSmitty** [comment]
Thanks, @remy! 👍🏼
