### ISSUE TITLE
HTTP status codes in the API

### ISSUE THREAD

**Issue by batuhan** [remy/mit-license#73]
In the API we create user files, I think API should also return HTTP codes like 200 OK, 403 forbidden etc.

I was gonna add this and send a PR but I'm not sure which HTTP status codes to return.

Any ideas?

**Comment by benniemosher** [comment]
@remy @batuhan Where does this Issue stand? Did we ever get this resolved? If not can we get an update so that we can continue working on it? If it has been addressed, resolved, or is no longer an issue then let's go ahead and close out this issue.
