### ISSUE TITLE
update mit-license page

### ISSUE THREAD

**Issue by yimengtianya** [remy/mit-license#730]
Hi , http://wilddog.mit-license.org/ seems to not contain email and url .
can you update it ?

Thanks for you work~

**Comment by benniemosher** [comment]
@yimengtianya Can you please open a PR and follow these instructions to update your `users/wilddog.json` file. I am uncertain, but it appears to me that the reason that this may not be updating is that your JSON file is not broken down on to separate lines. If you copy the JSON out of your file and paste it into this website, it should allow you to work your JSON until it is valid. http://jsonlint.com/

**Comment by yimengtianya** [comment]
Ok,I will try it,thank you~

**Comment by remy** [comment]
Looks to be working again.

**Comment by remy** [comment]
Wow, also, sorry, several months later!
