### ISSUE TITLE
Added user via curl but no .json file created

### ISSUE THREAD

**Issue by shagunsodhani** [remy/mit-license#751]
I added myself using the curl command : `curl -d'{ "copyright": "Shagun Sodhani", "url": "https://shagunsodhani.in", "email": "sshagunsodhani@gmail.com", "format": "txt" }' http://shagun.mit-license.org` 

The site is live [here](http://shagun.mit-license.org/) but no .json file was created in the [user directory](https://github.com/remy/mit-license/blob/master/users/shagun.json). I wanted to update the theme so how do I go about it.

**Comment by cheppsn** [comment]
Same question here. I observed the same behavior.

**Comment by ternaryalchemy** [comment]
Same here. I added myself using the curl command: `url -d'{ "copyright": "Rick Culpepper", "url": "http://ternaryalchemy.com", "email": "rick@ternaryalchemy.com", "format": "html" }' http://rcta.mit-license.org`
My site is live at http://rcta.mit-license.org/, but like @shagunsodhani, I do not find the corresponding .json file at https://github.com/remy/mit-license/blob/master/users/rcta.json.

**Comment by remy** [comment]
These are all fixed now.
