### ISSUE TITLE
License array is now Not valid metadata

### ISSUE THREAD

**Issue by andreasonny83** [remy/mit-license#787]
According to [NPM](https://docs.npmjs.com/files/package.json#license), the following expressions are no longer supported in the `package.json`:

```
// Not valid metadata
{ "license" :
  { "type" : "ISC"
  , "url" : "http://opensource.org/licenses/ISC"
  }
}

// Not valid metadata
{ "licenses" :
  [
    { "type": "MIT"
    , "url": "http://www.opensource.org/licenses/mit-license.php"
    }
  , { "type": "Apache-2.0"
    , "url": "http://opensource.org/licenses/apache2.0.php"
    }
  ]
}
```

Any idea how to point the license filed to a valid URL recognised by NPM?

They suggest to use this syntax instead:

If you are using a license that hasn't been assigned an SPDX identifier, or if you are using a custom license, use a string value like this one:

```
{ "license" : "SEE LICENSE IN <filename>" }
```

Then include a file named <filename> at the top level of the package.

But, I think this require a `LICENSE` file in the same folder. Any idea how to point that to an URL in order to conue using this mit-license service?

**Comment by Richienb** [comment]
@andreasonny83 This seems to have been fixed in https://github.com/remy/mit-license/commit/a5e4e4066d0a4f094ac30ec0a91638db160b92932.
