### ISSUE TITLE
GitHub pages as hosting

### ISSUE THREAD

**Issue by bfred-it** [remy/mit-license#880]
It might be late to change things now but it'd be great to have it hosted on GitHub. For free. With an automated generation.

Here's how it could work:

* URLs would be https://mit-license.org/username
* Usernames can only be added via PR
* PR would be a single file, Jekyll would take care of template generation
* A bot on Travis would verify the PR and automatically pull it or reject it

Advantages:

* Free hosting
* No risk of downtime (i.e. no need to mess with it, ever)
* Zero human interaction 🎉

Disadvantages:

* No automatic `2009-2010` year creation unless you also have a bot that is notified on 404 and creates the page for the next visit. Alternatively it's just a one-line PR away. Or it can be added via JS on the client.
* No curl, but maybe a new command could be crafted to do it from cli

Notes for the change:

* You'll probably need to setup redirects from the existing URLs to the new URLs, but this might be easy if your registrar offers redirects directly
* License versioning should just be updated to specific numbers rather than commits, to simplify automated page creation. `/v1` instead of `/a526bf7ad1`

**Comment by remy** [comment]
This would actually break all the existing URLs that point to the project though (since the username has moved in a non-backward compatible way).

Decent idea, but there's no support for the existing CNAME based urls (sorry, having to close because of that).

**Comment by bfred-it** [comment]
> * You'll probably need to setup redirects from the existing URLs to the new URLs, but this might be easy if your registrar offers redirects directly

It's in the notes. All it takes is a good domain registrar or a catch-all CNAME that points to a nano server with the redirect rules. It not effortless but it can be done
